version: '3.8'

services:
    wa-dev:
        container_name: wa_dev
        image: wa:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./docker/images/Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    # wa-prod:
    #     container_name: wa_prod
    #     image: wa:1.0.0
    #     build:
    #         context: .
    #         target: production
    #         dockerfile: ./docker/images/Dockerfile
    #     command: npm run start:prod
    #     ports:
    #         - 3000:3000
    #         - 9229:9229
    #     networks:
    #         - nesjs-network
    #     volumes:
    #         - .:/usr/src/app
    #         - /usr/src/app/node_modules
    #     restart: unless-stopped
    wa-db:
      image: mysql:5.7
      ports:
        - 3307:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
        MYSQL_PASSWORD: root
      command: --default-authentication-plugin=mysql_native_password
      restart: unless-stopped
      volumes:
        - dbmysql:/var/lib/mysql
      networks:
        - nesjs-network

networks:
    nesjs-network:
volumes:
      dbmysql:
        driver: "local"
  
